### ISSUE TITLE
Pad issue

### ISSUE THREAD

**Issue by koder1337** [neverlosecc/source2sdk#1]
Saying as short as possible, there is a bug in /or smth wrong with/ the gen.
Missing a few (pad) bytes. Saw it when i was looking at the DOTAGameRules structure.

[client.hpp : 4182 ]
You will see there is no pad between 0x8 and 0x30 position;
https://github.com/neverlosecc/source2sdk/blob/9e7f47e65dae489fd5a654eca342e14e61eee8f2/sdk/client.hpp#LL4182C10-L4182C10

**Comment by es3n1n** [comment]
Hey, nice catch! 
Sorry for the delayed response, I barely check this repo. 
Can you confirm that the bug still remains unfixed on the latest version of the source2gen project? If so, please reopen this issue in the https://github.com/neverlosecc/source2gen repo. Closing this as unplanned.

**Comment by koder1337** [comment]
do you know how to bypass BattlEye?
